package se.messme;

public enum Event {
	WRONG_EMAIL,
	WRONG_PASSWORD,
	AUTH_CORRECT,
	REGISTER_USER_SUCCESS,
	REGISTER_USER_FAILED,
	ADD_CONTACT_SUCCESS,
	ADD_CONTACT_FAILED,
	CREATE_GROUP_SUCCESS,
	CREATE_GROUP_FAILED,
	ADD_CONTACT_TO_GROUP_SUCCESS,
	ADD_CONTACT_TO_GROUP_FAILED,
	CREATE_MESSAGE_SUCCESS,
	CREATE_MESSAGE_FAILED,
	FAILED_TO_CREATE_SESSION,
	CREATE_DEVICE_FAILED,
	CREATE_DEVICE_SUCCESS,
	CHANGE_MESSAGE_STATUS_SUCCESS,
	CHANGE_MESSAGE_STATUS_FAILED,
	REMOVE_CONTACT_SUCCESS,
	REMOVE_CONTACT_FAILED,
	REMOVE_SESSION_SUCCESS,
	REMOVE_SESSION_FAILED;
}

	
